---
name: CI
"on":
  pull_request:
  push:
    branches:
      - main

jobs:

  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - debian

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install test dependencies.
        run: pip3 install ansible-dev-tools molecule-docker

      - name: Run YAML linting.
        run: yamllint .

      - name: Run Ansible linting.
        run: ansible-lint

      - name: Run Molecule tests.
        run: molecule test
        env: # Set environment variables for Molecule test
          PY_COLORS: "1" # Force color output for Molecule
          ANSIBLE_FORCE_COLOR: "1" # Force color output for Ansible
          MOLECULE_DISTRO: ${{ matrix.distro }}
